### ISSUE TITLE
Calculate a custom tip: Android Basics with Compose  

### ISSUE THREAD

**Issue by michealmachine** [google-developer-training/basic-android-kotlin-compose-training-tip-calculator#188] opened 2024-03-26 07:48 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-calculate-tip?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-3%3Fhl%3Dzh-cn%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-calculate-tip#5

**In which task and step of the codelab can this issue be found?**
6 step

**Describe the problem**
wrong code demonstrate

**Steps to reproduce?**
6.Add a switch

**Additional information**
wrong code:
       Switch(
           modifier = modifier<- wrong
               .fillMaxWidth()
               .wrapContentWidth(Alignment.End),
           //...
       )
is Modifier instead modifier

**Comment by android-dev-lxl** [comment] 2024-04-05 04:55
@michealmachine 
Thank you for reporting this issue.
This is fixed and published soon.

Duplicate of #189

**Closed by android-dev-lxl** 2024-04-05 04:55 UTC
