### ISSUE TITLE
Intro to state in Compose: Android Basics with Compose

### ISSUE THREAD

**Issue by elsbit** [google-developer-training/basic-android-kotlin-compose-training-tip-calculator#80] opened 2023-03-20 16:41 UTC
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-compose-using-state?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-using-state#10

**In which task and step of the codelab can this issue be found?**
Display the tip amount
 -> Use the calculateTip() function
  -> In TipTimeScreen()  composable function, call the [toDoubleOrNull](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.text/to-double-or-null.html) function on the amountInput variable, to convert the String to a Double:

**Describe the problem**
Hey, nice work! i love this training stuff. there is a tiny mistake in text:
TipTimeScreen() should mean EditNumberField()

have a nice day!

**Comment by osuleymanova** [comment] 2023-04-05 18:38
Duplicate of #78

**Comment by android-dev-lxl** [comment] 2023-07-24 21:22
@elsbit 
Thank you for reaching out to us.
Fixed and duplicate of #97

**Closed by android-dev-lxl** 2023-07-24 21:22 UTC
