### ISSUE TITLE
Intro to state in Compose: Android Basics with Compose

### ISSUE THREAD

**Issue by PhysMaths** [google-developer-training/basic-android-kotlin-compose-training-tip-calculator#92] opened 2023-04-18 20:09 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-using-state?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-using-state#10

**In which task and step of the codelab can this issue be found?**
task 11 
step: use the calculate tip() function

**Describe the problem**
in step 1 it says in tipTimeScreen() composable function you do so and so. However it should say the EditNumberField() composable function

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![image](https://user-images.githubusercontent.com/96183973/232893451-d1b33d97-c50f-41b7-8ce5-59fe06e383f3.png)

**Comment by osuleymanova** [comment] 2023-04-19 22:16
Duplicate of #90, #88, #85, #83, #82, #80, #78.

**Comment by android-dev-lxl** [comment] 2023-07-24 21:13
@PhysMaths 
This is fixed now. Thank you for your help. 
https://github.com/google-developer-training/basic-android-kotlin-compose-training-tip-calculator/issues/97

**Closed by android-dev-lxl** 2023-07-24 21:13 UTC
