### ISSUE TITLE
Intro to state in Compose: Android Basics with Compose

### ISSUE THREAD

**Issue by TheDani1** [google-developer-training/basic-android-kotlin-compose-training-tip-calculator#88] opened 2023-04-11 11:24 UTC
[**URL of codelab**](https://developer.android.com/codelabs/basic-android-kotlin-compose-using-state)

Cómo usar la función calculateTip().

Error in translatation. In the first step the code is not written down in TipTimeScreen(). It is written down in EditNumberField().

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![image](https://user-images.githubusercontent.com/21023099/231146985-34a6ac21-9052-41e5-b151-7c8fcf722ba0.png)

**Comment by osuleymanova** [comment] 2023-04-11 20:04
Duplicate of #85, #83, #82, #80, #78.

**Comment by android-dev-lxl** [comment] 2023-07-24 21:18
@TheDani1 
Thank you for reaching out to us.
Duplicate of #97

**Closed by android-dev-lxl** 2023-07-24 21:18 UTC
