### ISSUE TITLE
Calculate a custom tip: Android Basics with Compose  

### ISSUE THREAD

**Issue by peladno** [google-developer-training/basic-android-kotlin-compose-training-tip-calculator#184] opened 2024-03-16 15:04 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-calculate-tip?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-3%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-calculate-tip#5

**In which task and step of the codelab can this issue be found?**

Step number 6(Add switch) on the task number 8.

**Describe the problem**
In the composable Switch, on the modifier should be modifier = Modifier (in the example look like: modifer = modifier). Because is the class not a parameter

**Steps to reproduce?**
1. Go to step number 6 (Add a Switch)
2. scroll to point number 8

**Versions**
_Android Studio version: Android Studio Iguana | 2023.2.1
_API version of the emulator: 28

**Additional information**
![Screenshot 2024-03-17 at 12 00 11 AM](https://github.com/google-developer-training/basic-android-kotlin-compose-training-tip-calculator/assets/95249621/38948882-7bc1-46a0-839a-99681ef76c7a)

**Comment by android-dev-lxl** [comment] 2024-04-05 05:27
@peladno 
Thank you for reporting this issue.
This is fixed and published soon.
Duplicate of #189

**Closed by android-dev-lxl** 2024-04-05 05:27 UTC
Labels: duplicate, To be published
