### ISSUE TITLE
Intro to state in Compose: Android Basics with Compose

### ISSUE THREAD

**Issue by Jidni** [google-developer-training/basic-android-kotlin-compose-training-tip-calculator#82] opened 2023-04-01 21:54 UTC
[**URL of codelab**](https://developer.android.com/codelabs/basic-android-kotlin-compose-using-state?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-using-state#10)

**In which task and step of the codelab can this issue be found?**

Intro to state in Compose->Display the tip amount

**Describe the problem**

in the "Use the calculateTip() function" partition at step 1,
intruction is "In TipTimeScreen() composable function, ...",
it should be "In EditNumberField() composable function, ..."

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![image](https://user-images.githubusercontent.com/56132387/229315769-36a0738b-2366-4e2c-9d10-d4fa06504878.png)

**Comment by osuleymanova** [comment] 2023-04-05 18:38
Duplicate of #80, #78

**Comment by android-dev-lxl** [comment] 2023-07-24 21:21
@Jidni 
Thank you for reaching out to us.
Fixed and duplicate of #97

**Closed by android-dev-lxl** 2023-07-24 21:21 UTC
