### ISSUE TITLE
Write automated tests: Test folder missing

### ISSUE THREAD

**Issue by joshua41057** [google-developer-training/basic-android-kotlin-compose-training-tip-calculator#64] opened 2023-01-30 04:43 UTC
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-compose-write-automated-tests?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-write-automated-tests#3

**In which task and step of the codelab can this issue be found?**

Step4. 
> Create the test class
1. In the Project tab, click app > test and then click the d4706c21930a1ef3.png expander arrow next to the test directory.

**Describe the problem**

issue: There's no 'test' directory in the starter code. It is only in the solution code. So I should have to make it myself.

**Steps to reproduce?**
1. Go to...
3. Click on...
4. See error...

**Versions**
_Android Studio version:_ Android Studio Electric Eel | 2022.1.1
_API version of the emulator:_ Pixel 5 API 30

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![android1](https://user-images.githubusercontent.com/79959438/215389155-e73bb3b1-5246-4911-a2bd-907b8d7a6379.png)
![android2](https://user-images.githubusercontent.com/79959438/215389168-72372d62-f379-4cfd-b556-9244fbc1aaf9.png)

**Comment by android-dev-lxl** [comment] 2023-03-03 01:56
Duplicate of #61

**Comment by osuleymanova** [comment] 2023-03-09 00:09
Hello @joshua41057,

Thank you for reaching out to us and sharing your concern. Please check out the latest fixes in the repository, as well as the codelab content update.

**Closed by osuleymanova** 2023-03-09 00:09 UTC
