### ISSUE TITLE
Intro to state in Compose: Android Basics with Compose

### ISSUE THREAD

**Issue by hamman84** [google-developer-training/basic-android-kotlin-compose-training-tip-calculator#83] opened 2023-04-03 07:38 UTC
[**URL of codelab**](https://developer.android.com/codelabs/basic-android-kotlin-compose-using-state?authuser=1&hl=es-419&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-3%3Fhl%3Des-419%26authuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-using-state#10)

*Cómo usar la función calculateTip().

En ésta línea:
*En la función de componibilidad TipTimeScreen(), llama a la función [toDoubleOrNull] en la variable amountInput para convertir String en Double:*

La función de componibilidad que debería mencionar es: EditNumberField()

**Comment by android-dev-lxl** [comment] 2023-07-24 21:21
@hamman84 
Thank you for reaching out to us.
Fixed and duplicate of #97

<img width="1322" alt="image" src="https://github.com/google-developer-training/basic-android-kotlin-compose-training-tip-calculator/assets/24260141/e3a26bf6-62a2-4a60-aea2-4343381665db">

**Closed by android-dev-lxl** 2023-07-24 21:21 UTC
Labels: localization
