### ISSUE TITLE
Intro to state in Compose: Android Basics with Compose

### ISSUE THREAD

**Issue by PeterS-ZH** [google-developer-training/basic-android-kotlin-compose-training-tip-calculator#78] opened 2023-03-18 17:29 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-using-state?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-using-state#10

**In which task and step of the codelab can this issue be found?**
Unit 2
PW 3
CL 3
Step 11 "Display the tip amount"

**Describe the problem**

The instruction is:
"In TipTimeScreen() composable function, call the [toDoubleOrNull](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.text/to-double-or-null.html) function on the amountInput variable, to convert the String to a Double:"

A few lines further down, the new variables appear in the EditNumberField function... 

Pls see attached screen shot

**Steps to reproduce?**

Just need to check the documentation.

**Versions**
N/A

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![FireShot Capture 298 - Intro to state in Compose - developer android com](https://user-images.githubusercontent.com/127112741/226123164-43854e3c-1bc1-4f5c-8e6c-5db5b3c71278.png)

**Comment by android-dev-lxl** [comment] 2023-07-24 21:22
@PeterS-ZH 
Thank you for reaching out to us.
Fixed and duplicate of #97

**Closed by android-dev-lxl** 2023-07-24 21:22 UTC
