### ISSUE TITLE
Calculate a custom tip: Android Basics with Compose  

### ISSUE THREAD

**Issue by frankzx** [google-developer-training/basic-android-kotlin-compose-training-tip-calculator#17] opened 2022-06-26 04:04 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-calculate-tip?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-calculate-tip#4

**In which task and step of the codelab can this issue be found?**
[5. Set keyboard actions]

**Describe the problem**
the post states that 

> In the EditNumberField() function, add a val variable named focusManager and assign it a value of LocalFocusManager.current property:

`val focusManager = LocalFocusManager.current`

however, it should be in the `TipTimeScreen()` function

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by correabuscar** [comment] 2022-07-22 05:19
looks fixed now:
![fixed](https://user-images.githubusercontent.com/106607441/180368066-fa6e0312-35f4-42c2-9186-e2a4a7615b18.png)

**Comment by osuleymanova** [comment] 2023-02-17 19:50
The issue is closed as fixed.

**Closed by osuleymanova** 2023-02-17 19:50 UTC
