### ISSUE TITLE
Write automated tests: Android Basics with Compose

### ISSUE THREAD

**Issue by KamogaRonnieKigongo** [google-developer-training/basic-android-kotlin-compose-training-tip-calculator#124] opened 2023-06-20 09:23 UTC
**fun calculateTip(amount: Double, tipPercent: Double: roundUp: Boolean)**.......this line has an issue in the code lab

**Comment by android-dev-lxl** [comment] 2023-07-21 22:39
Duplicate of https://github.com/google-developer-training/basic-android-kotlin-compose-training-tip-calculator/issues/126

**Closed by android-dev-lxl** 2023-07-21 22:39 UTC
Labels: duplicate
