### ISSUE TITLE
Intro to state in Compose: Android Basics with Compose

### ISSUE THREAD

**Issue by alex-williams** [google-developer-training/basic-android-kotlin-compose-training-tip-calculator#89] opened 2023-04-12 09:34 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-using-state?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-using-state#10

**In which task and step of the codelab can this issue be found?**
Step 11 - Use the calculateTip() function - Task 1, 2 and 3

**Describe the problem**
The task says:
1. In TipTimeScreen() composable function, call the [toDoubleOrNull](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.text/to-double-or-null.html) function on the amountInput variable, to convert the String to a Double:

The instruction implies the 'amount' variable already exists and you're simply adding something to its declaration, but you actually need to create that new variable and then apply the toDoubleOrNull() function on the amountInput variable while assigning the result to the new 'amount' variable. This action is also not required in the TipTimeScreen() composable function as the instruction suggests, it is actually required in the EditNumberField() composable. The code snippets in the tasks do make this clear to people already familiar with coding, but could cause issues for people less familiar with programming.

**Steps to reproduce?**
1. Simply read tasks 1 - 3 in Step 11 within the Codelab

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by android-dev-lxl** [comment] 2023-07-24 21:17
@alex-williams 
Thank you for reaching out to us.
Duplicate of #97

**Closed by android-dev-lxl** 2023-07-24 21:17 UTC
