### ISSUE TITLE
Intro to state in Compose: Android Basics with Compose

### ISSUE THREAD

**Issue by SafiullahKakkar** [google-developer-training/basic-android-kotlin-compose-training-tip-calculator#90] opened 2023-04-14 17:33 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-using-state?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-3%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-using-state#10

**In which task and step of the codelab can this issue be found?**

11-Display the tip amount -> Use the calculateTip() function
**Describe the problem**
There's a writing mistake. The "amountInput" variable exists in the "EditNumberField" function. But the instruction says otherwise: 
In TipTimeScreen() composable function, call the [toDoubleOrNull] function on the amountInput variable...

**Steps to reproduce?**
1. Go to the link of the codelab
2. Scroll down the page until you find the "Use the calculateTip() function" title. 
3. Read the step #1 to see the error.

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment] 2023-04-17 19:44
Duplicate of #85, #83, #82, #80, #78

**Comment by android-dev-lxl** [comment] 2023-07-24 21:14
@SafiullahKakkar 
Thank you for reaching out to us.
Duplicate of https://github.com/google-developer-training/basic-android-kotlin-compose-training-tip-calculator/issues/97

**Closed by android-dev-lxl** 2023-07-24 21:14 UTC
