### ISSUE TITLE
Calculate a custom tip: Android Basics with Compose  

### ISSUE THREAD

**Issue by RazoTRON** [google-developer-training/basic-android-kotlin-compose-training-tip-calculator#9] opened 2022-06-03 11:44 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-calculate-tip?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-calculate-tip#4

**In which task and step of the codelab can this issue be found?**
Unit 2, PATHWAY 3, #4 "Calculate a custom tip", step #5 "Set keyboard actions"

**Describe the problem**
"In the EditNumberField() function, add a val variable named focusManager and assign it a value of LocalFocusManager.current"
change to: 
"In the TipTimeScreen() function, add a val variable named focusManager and assign it a value of LocalFocusManager.current"

**Comment by osuleymanova** [comment] 2022-06-21 23:30
Duplicate of #6, #4, #2

**Comment by osuleymanova** [comment] 2022-06-22 19:56
@RazoTRON 
Thank you for reaching out to us. The typo is fixed and will be published soon:


![Screen Shot 2022-06-22 at 12 48 44 PM](https://user-images.githubusercontent.com/86437155/175124763-069959e3-632d-4187-ad86-8c3cfa42a80b.png)

**Closed by osuleymanova** 2022-06-22 19:56 UTC
