### ISSUE TITLE
Calculate a custom tip: Android Basics with Compose  

### ISSUE THREAD

**Issue by EhIvan** [google-developer-training/basic-android-kotlin-compose-training-tip-calculator#11] opened 2022-06-14 20:25 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-calculate-tip?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-calculate-tip#4

**In which task and step of the codelab can this issue be found?**
Calculate a custom tip -> [5. Set keyboard actions]

**Describe the problem**
Wrong text decsription:
/*
In the EditNumberField() function, add a val variable named focusManager and assign it a value of LocalFocusManager.current property:
*/

This val should bee add in the fun TipTimeScreen

**Comment by osuleymanova** [comment] 2022-06-22 19:59
Duplicate of #2, #4, #6, #8, #9

**Comment by osuleymanova** [comment] 2022-06-22 20:00
@EhIvan 
Thank you for reaching out to us. The typo is fixed and will be published soon:

![Screen Shot 2022-06-22 at 12 48 44 PM](https://user-images.githubusercontent.com/86437155/175125472-065f5773-9210-4c0a-a52a-071c4f3059b4.png)

**Closed by osuleymanova** 2022-06-22 20:00 UTC
