### ISSUE TITLE
Calculate a custom tip: Android Basics with Compose  

### ISSUE THREAD

**Issue by sebbefyhr** [google-developer-training/basic-android-kotlin-compose-training-tip-calculator#186] opened 2024-03-22 14:23 UTC
[**URL of codelab**](https://developer.android.com/codelabs/basic-android-kotlin-compose-calculate-tip?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-calculate-tip#5)

**In which task and step of the codelab can this issue be found?**
Task: add a switch step 2.

**Describe the problem**

in the example code (the code provided by you, there is a declaration as follows:

Row( modifier = modifier
.fill....

it is this second modifier that should have a capital M as: modifier = Modifier

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by android-dev-lxl** [comment] 2024-04-05 04:56
@michealmachine 
Thank you for reporting this issue.
This is fixed and published soon.

Duplicate of #189

**Closed by android-dev-lxl** 2024-04-05 04:56 UTC
Labels: duplicate
