### ISSUE TITLE
Intro to state in Compose: Android Basics with Compose

### ISSUE THREAD

**Issue by svkg019** [google-developer-training/basic-android-kotlin-compose-training-tip-calculator#85] opened 2023-04-05 09:33 UTC
**URL of code lab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-using-state?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-using-state#10

**In which task and step of the code lab can this issue be found?**
11. Display the tip amount

**Describe the problem**
The function name should be EditNumberField() instead of TipTimeScreen() 

**Additional information**
![Screenshot 2023-04-05 145759](https://user-images.githubusercontent.com/107418374/230041267-79566a07-001a-4b03-8da3-a0d648f7e7e1.png)

**Comment by osuleymanova** [comment] 2023-04-05 18:35
Duplicate of #83

**Comment by android-dev-lxl** [comment] 2023-07-24 21:18
@svkg019 
Thank you for reaching out to us.
Duplicate of #97

**Closed by android-dev-lxl** 2023-07-24 21:18 UTC
